# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [7]:
from dataclasses import field
from gettext import install

### Assignment 1: Array Creation and Manipulation

# 1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20.
# Replace all the elements in the third column with 1.


import numpy as np
from numpy.ma.core import masked_greater

arr = np.random.randint(1, 21, size=(5, 5))
arr[:, 2] = 1
print(arr)





[[ 8 18  1  6  7]
 [20 17  1  5  6]
 [17  7  1  4  8]
 [19 17  1 10  8]
 [ 7 19  1 10  2]]


In [9]:
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.


arr = np.random.randint(1, 17, size=(4,4))

np.fill_diagonal(arr, 0)
print(arr)

[[ 0  1  9 11]
 [ 8  0  5  2]
 [14  3  0  2]
 [ 6  4  1  0]]


In [15]:
### Assignment 2: Array Indexing and Slicing

# 1. Create a NumPy array of shape (6, 6) with values from 1 to 36.
# Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

arr1=np.random.randint(1, 37, size=(6,6))
print(arr1)
print(arr1.shape)
print(arr1[2:5,1:4])

[[33 10 28 10 17 14]
 [30 20 22 34 33 25]
 [31 12  7  4  9  8]
 [31 36  5 28 29  4]
 [12 20  2 23 16  2]
 [19 17 27 12 25  5]]
(6, 6)
[[ 7  4]
 [ 5 28]
 [ 2 23]]


In [18]:
# 2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

arr2=np.random.randint(1,26,size=(5,5))
print(arr2)

border = np.concatenate([
    arr2[0, :],      # top row
    arr2[-1, :],     # bottom row
    arr2[1:-1, 0],   # left column (excluding corners)
    arr2[1:-1, -1]   # right column (excluding corners)
])

print(border)


[[ 4  5 19  2  9]
 [11 15 20 19 22]
 [24  9  5 23 13]
 [14  4 25 14  7]
 [ 5  4 13  7 11]]
[ 4  5 19  2  9  5  4 13  7 11 11 24 14 22 13  7]


In [22]:
### Assignment 3: Array Operations

# 1. Create two NumPy arrays of shape (3, 4) filled with random integers.
# Perform element-wise addition, subtraction, multiplication, and division.

arr3=np.random.randint(1,12,size=(3,4))
arr4=np.random.randint(1,12,size=(3,4))
print(f"array 1:{arr3}")
print(f"array 2 :{arr4}")

print(f"addition {arr3+arr4}")
print(f"subtraction {arr3-arr4}")
print(f"multiplication {arr3*arr4}")
print(f"division {arr3*arr4}")

array 1:[[ 3 10  4  1]
 [ 2  7  4  7]
 [ 7  9  5  6]]
array 2 :[[ 4 11  4  8]
 [ 2  7 10  3]
 [ 9 10  2  2]]
addition [[ 7 21  8  9]
 [ 4 14 14 10]
 [16 19  7  8]]
subtraction [[-1 -1  0 -7]
 [ 0  0 -6  4]
 [-2 -1  3  4]]
multiplication [[ 12 110  16   8]
 [  4  49  40  21]
 [ 63  90  10  12]]
division [[ 12 110  16   8]
 [  4  49  40  21]
 [ 63  90  10  12]]


In [26]:
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

arr5=np.random.randint(1,16,size=(4,4))
print(arr5)

# Row-wise sum
row_sum = np.sum(arr5, axis=1)

# Column-wise sum
col_sum = np.sum(arr5, axis=0)

print("Row-wise sum:")
print(row_sum)

print("\nColumn-wise sum:")
print(col_sum)

[[ 3  2  8 12]
 [ 8  4  8 11]
 [14  7  3 11]
 [ 9  5  6  3]]
Row-wise sum:
[25 31 35 23]

Column-wise sum:
[34 18 25 37]


In [28]:
### Assignment 4: Statistical Operations

# 1. Create a NumPy array of shape (5, 5) filled with random integers.
# Compute the mean, median, standard deviation, and variance of the array.

arr6=np.random.randint(1,26,size=(5,5))
print(arr6)
print(f"mean {np.mean(arr6)}")
print(f"std {np.std(arr6)}")
print(f"median {np.median(arr6)}")
print(f"variance {np.var(arr6)}")

[[ 4 19  5 16 24]
 [15 10 16  2 15]
 [11 25 23  6 24]
 [23 10 12 19 20]
 [17  3 20 11 14]]
mean 14.56
std 6.870691377146844
median 15.0
variance 47.206399999999995


In [30]:
# 2. Create a NumPy array of shape (3, 3) with values from 1 to 9.
# Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

arr7=np.random.randint(1,10,size=(3,3))
print(arr7)
nor_dev=(arr7-np.mean(arr7)/np.std(arr7))
print(f"normal deviation: {nor_dev}")

[[5 2 3]
 [5 9 8]
 [2 2 7]]
normal deviation: [[3.14268289 0.14268289 1.14268289]
 [3.14268289 7.14268289 6.14268289]
 [0.14268289 0.14268289 5.14268289]]


In [31]:

### Assignment 5: Broadcasting

# 1. Create a NumPy array of shape (3, 3) filled with random integers.
# Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
# Create a 3x3 array with random integers
arr_2d = np.random.randint(1, 10, size=(3, 3))

# Create a 1D array of shape (3,)
arr_1d = np.array([1, 2, 3])

# Add the 1D array to each row using broadcasting
result = arr_2d + arr_1d

print("Original 2D Array:")
print(arr_2d)

print("\n1D Array:")
print(arr_1d)

print("\nResult:")
print(result)

Original 2D Array:
[[5 7 3]
 [1 3 2]
 [1 4 8]]

1D Array:
[1 2 3]

Result:
[[ 6  9  6]
 [ 2  5  5]
 [ 2  6 11]]


In [33]:
# 2. Create a NumPy array of shape (4, 4) filled with random integers.
# Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

arr1_2d=np.random.randint(1, 17, size=(4,4))
print(f"array: {arr1_2d}")
arr2_2d=np.array([1,2,3,4])
print(f"array: {arr2_2d}")
sub=arr1_2d-arr2_2d
print(f"sub: {sub}")


array: [[13  2  8  4]
 [10  3 15  1]
 [11  8 12 12]
 [ 5 16  4 10]]
array: [1 2 3 4]
sub: [[12  0  5  0]
 [ 9  1 12 -3]
 [10  6  9  8]
 [ 4 14  1  6]]


In [4]:
### Assignment 6: Linear Algebra

# 1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
import numpy as np
arr_linear=np.random.randint(1, 10, size=(3, 3))
print(f"array: {arr_linear}")
determinant=np.linalg.det(arr_linear)
print(f"determinant: {determinant}")
inverse=np.linalg.inv(arr_linear)
print(f"inverse: {inverse}")
eigenvalues=np.linalg.eig(arr_linear)
print(f"eigenvalues: {eigenvalues}")


array: [[3 8 8]
 [5 7 9]
 [5 7 1]]
determinant: 152.0
inverse: [[-0.36842105  0.31578947  0.10526316]
 [ 0.26315789 -0.24342105  0.08552632]
 [-0.          0.125      -0.125     ]]
eigenvalues: EigResult(eigenvalues=array([17.78002122, -1.67442011, -5.10560111]), eigenvectors=array([[-0.60147223, -0.77250181, -0.34853657],
       [-0.65765121,  0.61386991, -0.46224638],
       [-0.45357032, -0.16249516,  0.81538368]]))


In [8]:
# 2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

mul_arr=np.array([[1,2,3],[4,5,6]])
print(f"mul_arr: {mul_arr}")
mul_arr1=np.array([[7,8],[1,2],[5,6]])
print(f"mul_arr1: {mul_arr1}")
mul = mul_arr @ mul_arr1 #If you want Matrix Multiplication  Use @ or np.matmul()
print(f"mul: {mul}")

mul_arr: [[1 2 3]
 [4 5 6]]
mul_arr1: [[7 8]
 [1 2]
 [5 6]]
mul: [[24 30]
 [63 78]]


In [12]:
### Assignment 7: Advanced Array Manipulation

# 1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

adv_arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"adv_arr: {adv_arr}")
reshape_arr=np.reshape(adv_arr, (1,9))
print(f"reshape_arr: {reshape_arr}")
shape_arr=np.reshape(adv_arr, (9,1))
print(f"shape_arr: {shape_arr}")

adv_arr: [[1 2 3]
 [4 5 6]
 [7 8 9]]
reshape_arr: [[1 2 3 4 5 6 7 8 9]]
shape_arr: [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [18]:
# 2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).
arr_flat=np.arange(1, 26).reshape(5, 5)

print(f"arr_flat: {arr_flat}")
flat_arr=arr_flat.flatten()
print(f"flat_arr: {flat_arr}")
flat_reshape=np.reshape(flat_arr, (5,5))
print(f"flat_reshape: {flat_reshape}")

arr_flat: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
flat_arr: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
flat_reshape: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [20]:
### Assignment 8: Fancy Indexing and Boolean Indexing

# 1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
fancy_arr=np.random.randint(1,26,size=(5,5))
print(f"fancy_arr: {fancy_arr}")
corners = fancy_arr[[0, 0, 4, 4], [0, 4, 0, 4]]

print("\nCorner elements:")
print(corners)

fancy_arr: [[ 9  4 14  5 25]
 [ 6  2 21 19 15]
 [ 4 24 12  3  3]
 [ 1 25 20 12 25]
 [14 19 25 12  4]]

Corner elements:
[ 9 25 14  4]


In [26]:
# 2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.
bool_arr=np.random.randint(1,17,size=(4,4))
print(f"bool_arr: {bool_arr}")
# Set all elements greater than 10 to 10
bool_arr[bool_arr > 10] = 10

print("\nModified Array:")
print(bool_arr)

bool_arr: [[13 11  2 14]
 [ 3  2  7  8]
 [12  4  2  6]
 [10 16  8  6]]

Modified Array:
[[10 10  2 10]
 [ 3  2  7  8]
 [10  4  2  6]
 [10 10  8  6]]


In [34]:
### Assignment 9: Structured Arrays

# 1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float).
# Add some data and sort the array by age.
import numpy as np

# Define the structured data type
person_dtype = [('name', 'U20'), ('age', 'i4'), ('weight', 'f4')]

# Create the structured array
people = np.array([
    ('Alice', 25, 55.5),
    ('Bob', 30, 70.2),
    ('Charlie', 22, 68.0),
    ('David', 28, 75.3)
], dtype=person_dtype)

print("Original Array:")
print(people)

# Sort by age
sorted_people = np.sort(people, order='age')

print("\nSorted by Age:")
print(sorted_people)

Original Array:
[('Alice', 25, 55.5) ('Bob', 30, 70.2) ('Charlie', 22, 68. )
 ('David', 28, 75.3)]

Sorted by Age:
[('Charlie', 22, 68. ) ('Alice', 25, 55.5) ('David', 28, 75.3)
 ('Bob', 30, 70.2)]


In [36]:
# 2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

str_arr=[('x','i4'),('y','i4')]
field_arr=np.array([(10,20),
                    (20,30),
                    (30,40)],dtype=str_arr)
print(f"field_arr: {field_arr}")

# Compute distances between each pair of points
n = len(field_arr)

for i in range(n):
    for j in range(i + 1, n):
        dx = field_arr[j]['x'] - field_arr[i]['x']
        dy = field_arr[j]['y'] - field_arr[i]['y']

        distance = np.sqrt(dx**2 + dy**2)

        print(f"Distance between Point {i} and Point {j}: {distance:.2f}")


field_arr: [(10, 20) (20, 30) (30, 40)]
Distance between Point 0 and Point 1: 14.14
Distance between Point 0 and Point 2: 28.28
Distance between Point 1 and Point 2: 14.14


In [43]:
### Assignment 10: Masked Arrays

# 1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

mask_arr=np.random.randint(1,17,size=(4,4))
print(f"mask_arr: {mask_arr}")
mas_gr=np.ma.masked_greater(mask_arr, 10)
print(f"mass_gr: {mas_gr}")
mas_sum=mas_gr.sum()
print(f"mass_sum: {mas_sum}")


mask_arr: [[ 5  9 11 14]
 [ 3 12 13 10]
 [ 2  3  6 10]
 [ 4 16 14 15]]
mass_gr: [[5 9 -- --]
 [3 -- -- 10]
 [2 3 6 10]
 [4 -- -- --]]
mass_sum: 52


In [45]:
import numpy as np

# Create a 3x3 array with random integers from 1 to 20
arr = np.random.randint(1, 21, size=(3, 3))

print("Original Array:")
print(arr)

# Mask the diagonal elements
masked_arr = np.ma.masked_array(arr, mask=np.eye(3, dtype=bool))

print("\nMasked Array:")
print(masked_arr)

# Mean of unmasked elements
mean_value = masked_arr.mean()

print("\nMean of unmasked elements:")
print(mean_value)

# Replace masked elements with the mean
filled_arr = masked_arr.filled(mean_value)

print("\nArray after replacing masked elements:")
print(filled_arr)

Original Array:
[[ 2 15  9]
 [20  3 20]
 [ 8  2 19]]

Masked Array:
[[-- 15 9]
 [20 -- 20]
 [8 2 --]]

Mean of unmasked elements:
12.333333333333334

Array after replacing masked elements:
[[12 15  9]
 [20 12 20]
 [ 8  2 12]]
