In [2]:
import numpy
import numpy as np

arr = np.array([1, 2, 3])
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [7]:
arr2=numpy.array([4,5,6])
print(arr2.shape)
print(arr2.reshape(1,3))

(3,)
[[4 5 6]]


In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
print(arr.size)
print(arr2.ndim)
print(arr2.shape)
print(arr.itemsize)
print(arr.dtype)

3
1
(3,)
8
int64


In [13]:
print(arr+arr2)

[5 7 9]


In [17]:
print(np.sqrt(arr))
print(np.exp(arr))
print(np.log(arr))
print(np.sin(arr))

[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
[0.84147098 0.90929743 0.14112001]


In [19]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [20]:
import numpy as np

print(np.__version__)

2.3.2
